version: '3.8'

services:
    ganache-cli:
        image: trufflesuite/ganache-cli:latest
        ports:
          - 8545:8545

    mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017

    market_blockchain_api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - ./api/.env
        depends_on:
            - ganache-cli
            - mongo
        volumes:
            - /usr/src/app/node_modules
            - ./api/src:/usr/src/app/src

    market_blockchain_client:
        build:
            context: .
            dockerfile: ./client/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - /usr/src/client/node_modules
            - ./client/src:/usr/src/client/src
            - ./client/public:/usr/src/app/public